# ----------------------------
# Makefile Options
# ----------------------------

NAME = ZCALCONV
DESCRIPTION = "Convert calendars."
COMPRESSED = YES
ARCHIVED = YES

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
