# ----------------------------
# Makefile Options
# ----------------------------

NAME = STPWTCH
DESCRIPTION = "Stopwatch"
COMPRESSED = YES
ARCHIVED = YES

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
